dependencies:
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.14.1
  openai:
    url: github.com/toitware/toit-openai
    version: ^0.2.1
