dependencies:
  device_bot:
    url: github.com/floitsch/toit-device-bot
    version: ^0.2.1
  dhtxx:
    url: github.com/toitware/toit-dhtxx
    version: ^1.4.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.13.0
  telegram:
    url: github.com/floitsch/toit-telegram
    version: ^0.1.1
