dependencies:
  device_bot:
    url: github.com/floitsch/toit-device-bot
    version: ^0.1.0
  discord:
    url: github.com/floitsch/toit-discord
    version: ^0.1.0
  hc_sr04:
    url: github.com/lask/toit-hc-sr04
    version: ^2.0.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.3.0
  telegram:
    url: github.com/floitsch/toit-telegram
    version: ^0.1.0
